config/routes.rb
Rails.application.routes.draw do

  #Msgboardのルーティング情報
  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'
  get 'msgboard/index'
  post 'msgboard/index'
  
  #Sneakersのルーティング情報
  get 'sneakers/index'
  get 'sneakers', to: 'sneakers#index'
  get 'sneakers/add'
  post 'sneakers/add'
  get 'sneakers/:id', to:'sneakers#show'
  get 'sneakers/edit/:id', to:'sneakers#edit'
  patch 'sneakers/edit/:id', to:'sneakers#edit'
  get 'sneakers/delete/:id', to:'sneakers#delete'

  # Q&Aのルーティング設定（Scaffoldで作成）
  resources :answers
  resources :questions
  #  
  #Peopleクラス
#  get 'people/index'
#  get 'people', to: 'people#index'
#  get 'people/add'
#  post 'people/add', to: 'people#create'
#  get 'people/edit/:id', to: 'people#edit'
#  post 'people/edit/:id', to: 'people#update'
#  patch 'people/edit/:id', to: 'people#update'
#  get 'people/delete/:id', to: 'people#delete'
#  get 'people/find'
#  post 'people/find'
#  get 'people/:id', to: 'people#show'

  #Messageクラス
#  get 'messages/index'
#  get 'messages', to:'messages#index'
#  get 'messages/add'
#  post 'messages/add', to:'messages#create'
#  get 'messages/edit/:id', to:'messages#edit'
#  patch 'messages/edit/:id', to:'messages#update'
#  get 'messages/delete/:id', to:'messages#delete'
#  get 'messages/:id', to:'messages#show'

end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to:question

    validates :content, :name, presence:{message:'は、必須項目です。'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many:answer

    validates :content, :name, presence:{message:'は、必須項目です。'}
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
    validates :name, presence:{message:'は、必須項目です。'}
    validates :price, numericality:{only_integer:true, 
                                    greater_than:0, 
                                    message:'は、1以上の数値を入力してください。'}
    validates :color, color:{message:'はホワイト、ブラック、パープル、レッド、ブルーのみ入力可能です。'}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]
  layout 'Q&A'

  def new
    @answer = Answer.new
  end

  # 送信されたフォームの内容をAnswerに保存
  def create
    end_counter = 10  # 終了にする回答数
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        num = Answer.where('question_id = ?', @answer.question_id).count
        # 回答数が10以上の場合、ステータスを「終了」に更新
        if num >= end_counter then
          q = Question.find @answer.question_id
          q.finished = true
          q.save
        end
        format.html { redirect_to '/questions/' + @answer.question_id.to_s }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # 未使用のアクション（トップページに移動）
  def index
    redirect_to '/questions'
  end

  # 未使用のアクション（トップページに移動）
  def show
    redirect_to '/questions'
  end

  # 未使用のアクション（トップページに移動）
  def edit
    redirect_to '/questions'
  end
  
  # 未使用のアクション（トップページに移動）
  def update
    redirect_to '/questions'
  end

  # 未使用のアクション（トップページに移動）
  def destroy
    redirect_to '/questions'
  end

  private
    # 指定されたIDの回答を取得
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # params(answer)の項目チェック
    def answer_params
      params.require(:answer).permit(:question_id, :content, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/msgboard_controller.rb
class MsgboardController < ApplicationController
  layout 'msgboard'

  # コンストラクタ
  def initialize
    super
    # テキストファイルの読み込み
    begin
      @msg_data = JSON.parse(File.read("data.txt"))
    rescue
      @msg_data = Hash.new
    end
    # 24時間経過したデータを削除
    @msg_data.each do |key,obj|
      if Time.now.to_i - key.to_i > 24*60*60 then
        @msg_data.delete(key)
      end
    end
    # テキストファイルを保存
    File.write("data.txt", @msg_data.to_json)
  end

  # 画面表示処理
  def index
    if request.post? then
      # POST送信された場合
      obj = MyData.new(msg:params['msg'], name:params['name'], mail:params['mail'])
      @msg_data[Time.now.to_i] = obj
      # JSON型式で取り出す
      data = @msg_data.to_json
      # テキストファイルに保存
      File.write("data.txt", data)
      # JSON型式のデータからRubyオブジェクトを生成
      @msg_data = JSON.parse(data)
    end
  end

end

# データ保管用クラス
class MyData
  # インスタンス変数
  attr_accessor :name
  attr_accessor :mail
  attr_accessor :msg

  # コンストラクタ
  def initialize name:name1, mail:mail1, msg:msg1
    self.name = name
    self.mail = mail
    self.msg = msg
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  layout 'Q&A'

  # 質問の一覧表示（トップページ）
  def index
    # 全質問を取得（投稿日時の降順）
    @questions = Question.all.order created_at: :desc
  end

  # 質問と回答の表示
  def show
    @answer = Answer.new
    @answer.question_id = params[:id]
  end

  # 新しい質問の投稿
  def new
    @question = Question.new
  end

  # 送信されたフォームの内容をQuestionに保存
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new } 
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # 未使用のアクション（トップページに移動）
  def edit
    redirect_to '/questions'
  end
  
  # 未使用のアクション（トップページに移動）
  def update
    redirect_to '/questions'
  end

  # 未使用のアクション（トップページに移動）
  def destroy
    redirect_to '/questions'
  end

  private
    # 指定されたIDの回答を取得
    def set_question
      @question = Question.find(params[:id])
    end

    # params(question)の項目チェック
    def question_params
      params.require(:question).permit(:title, :content, :name, :finished)
    end
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  layout 'sneakers'

  # 全商品の一覧表示を行うホーム画面
  def index
    # 全商品情報を取得
    @sneakers = Sneaker.all
  end

  # 選択した商品の内容を表示
  def show
    # 指定されたIDの商品情報を取得
    @sneaker = Sneaker.find(params[:id])
  end

  # 商品情報の追加
  def add
    @msg = '※登録する商品データを入力してください。'
    if request.post? then
      # データを登録
      @sneaker = Sneaker.new sneaker_params
      if @sneaker.save then
        #ホーム画面へ戻る
        goback
      end
    else
      @sneaker = Sneaker.new
    end
  end

  # 商品情報の更新
  def edit
    # 指定されたIDの商品情報を取得
    @sneaker = Sneaker.find(params[:id])
    if request.patch? then
      # データを更新
      @sneaker.update(sneaker_params)
      goback
    end
  end

  # 商品情報の削除
  def delete
    # 指定されたIDのデータを削除
    Sneaker.find(params[:id]).destroy
    goback
  end

  # Privateメソッド
  private
  # params（sneaker）の項目チェック
  def sneaker_params
    params.require(:sneaker).permit(:name,:maker,:color,:price,:memo)
  end

  # ホーム画面に戻る
  def goback
    redirect_to '/sneakers'
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/msgboard_helper.rb
module MsgboardHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/answers/_form.html.erb
<%= form_for(answer) do |form| %>
  <% if answer.errors.any? %>
    <div class="text-danger" id="error_explanation">
      <h2>入力内容に誤りがあるため、回答を保存できませんでした:</h2>
      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Content</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.content %></td>
        <td><%= answer.name %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1 class="display-4 text-primary">New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'トップページに戻る', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/Q&A.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Q&A</title>
        <%= csrf_meta_tags %>
        <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'Q&A', media: 'all','data-turbolinks-track': 'reload' %>
    </head>
    <body class="container">
        <%= yield %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstap.css">
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/layouts/msgboard.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
</head>

<body class="container text-body">
    <h1 class="mb-4 display-4 text-primary">MsgBoard</h1>
    <%= yield %>
</body>
</html>

app/views/layouts/sneakers.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Sneakers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <style>
        h1 {margin:25px 0px;}
        p {margin:25px 0px;}
    </style>
</head>

<body class="container">
    <%= yield %>
</body>
</html>

app/views/msgboard/index.html.erb
<%= form_tag(cotroller: "msgboard", action: "index") do %>
    <div class="form-group">
        <label for="name">名前</label>
        <%= text_field_tag("name","",{class:"form-control"}) %>
    </div>
    <div class="form-group">
        <label for="name">メール</label>
        <%= text_field_tag("mail","",{class:"form-control"}) %>
    </div>
    <div class="form-group">
        <label for="name">メッセージ</label>
        <%= text_area_tag("msg","",{class:"form-control"}) %>
    </div>
    <%= submit_tag("Click", {class:"btn btn-primary"}) %>
<% end %>

<table class="table mt-4">
    <tr>
        <th style="width:50%">メッセージ</th>
        <th>名前</th>
        <th>メール</th>
        <th>投稿日時</th>
    </tr>
    <% @msg_data.each do |key,obj| %>
    <tr>
        <td class="msg"><%= obj['msg'] %></td>
        <td class="name"><%= obj['name'] %></td>
        <td class="mail"><%= obj['mail'] %></td>
        <td class="time"><%= Time.at(key.to_i) %></td>
    </tr>
    <% end %>
</table>

app/views/questions/_form.html.erb
  <% if question.errors.any? %>
    <div class="text-danger" id="error_explanation">
      <h2>入力内容に誤りがあるため、質問を保存できませんでした:</h2>
      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for(question) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, rows:5, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <%= f.hidden_field :finished, {value:false} %>

    <div>
      <%= f.submit %>
    </div>
  <% end %>

app/views/questions/_form2.html.erb
<% if answer.errors.any? %>
    <div class="text-danger" id="error_explanation">
        <h2>入力内容に誤りがあるため、回答を保存できませんでした:</h2>
        <ul>
        <% answer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= form_for(answer) do |f| %>
    <%= f.hidden_field :question_id, {value:answer.question_id} %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, rows:2, class:"form-control" %>
    </div>
    <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Questions</h1>

<table class="table mt-5 mb-5">
  <thead>
    <tr>
      <th>Title</th>
      <th>Finished</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.finished ? '終了' : '受付中' %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '※新たに質問する', new_question_path %>

app/views/questions/new.html.erb
<h1 class="display-4 text-primary">New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'トップページに戻る', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Question & Answers</h1>

<div class="jombotron p-4 mb-4">
  <h2 class="card-title">
    <%= @question.title %>
  </h2>
  <p class="card-text">
    <%= @question.content %>
  </p>
  <p class="blockquote-footer text-right">
    <%= @question.name %>
  </p>
  <div class="<%= @question.finished ? 'text-danger' : 'text-primary' %>">
    <%= @question.finished ? '終了' : '受付中' %>
  </div>
</div>

<% if @question.finished? == false then %>
  <div class="card p-3 mb-4">
    <h3 class="h4 text-primary">※回答する</h3>
    <%= render 'form2', answer:@answer %>
  </div>
<% end %>

<h3 class="h4 text-primary">※これまで寄せられた回答</h3>

<ul class="list-group">
<% if @question.answer.count == 0 then %>
  <p class="answer">※まだありません。</p>
<% else %>
  <% @question.answer.reverse_each do |re| %>
    <li class="list-group-item">
      <%= re.content + ' (' + re.name + ')' %>
    </li>
  <% end %>
<% end %>
</ul>

<%= link_to 'トップページに戻る', questions_path %>

app/views/sneakers/add.html.erb
<h1 class="display-4 text-primary">Sneakers#add</h1>
<p><%= @msg %></p>
<% if @sneaker.errors.any? %>
<ul>
    <% @sneaker.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
</ul>
<% end %>
<%= form_for(@sneaker, url:{controller:'sneakers', action:'add'}) do |form| %>
    <div class="form-group">
        <label for="name">Name</label>
        <%= form.text_field :name, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="maker">Maker</label>
        <%= form.text_field :maker, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="color">Color</label>
        <%= form.text_field :color, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <%= form.text_field :price, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="memo">Memo</label>
        <%= form.text_area :memo, {rows:5, class:"form-control"} %>
    </div>
    <%= form.submit "保存" %>
<% end %>
<p class="link"><a href="/sneakers">&lt;&lt;  ※トップページに戻る</a></p>

app/views/sneakers/edit.html.erb
<h1 class="display-4 text-primary">Sneakers#edit</h1>
<p>※「<%= @sneaker.name %>」の内容を編集します。</p>
<%= form_for(@sneaker, url:{controller:'sneakers', action:'edit', id:@sneaker.id}) do |form| %>
    <div class="form-group">
        <label for="name">Name</label>
        <%= form.text_field :name, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="maker">Maker</label>
        <%= form.text_field :maker, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="color">Color</label>
        <%= form.text_field :color, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <%= form.text_field :price, {class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="memo">Memo</label>
        <%= form.text_area :memo, {rows:5, class:"form-control"} %>
    </div>
    <%= form.submit "更新" %>
<% end %>
<p class="link"><a href="/sneakers">&lt;&lt;  ※トップページに戻る</a></p>

app/views/sneakers/index.html.erb
<h1 class="display-4 text-primary">Sneakers#index</h1>
<p>※現在、登録されている商品の一覧です。</p>
<table class="table">
    <tr>
        <th>ID</th><th>Name</th><th>Maker</th><th colspan="2"></th>
    </tr>
    <% @sneakers.each do |obj| %>
    <tr>
        <td width="35px"><%= obj.id %></td>
        <td width="50%"><a href="/sneakers/<%= obj.id %>"><%= obj.name %></a></td>
        <td><%= obj.maker %></td>
        <td width="80px"><a href="/sneakers/edit/<%= obj.id %>">編集</a></td>
        <td width="80px"><a href="javascript:delData(
                                    <%= (obj.id.to_s + ",'".to_s + 
                                         obj.name.to_s).html_safe %>');">削除</a></td>
    </tr>
    <% end %>
</table>
<p><a href="/sneakers/add">★新規登録★</a></p>
<script>
function delData(id,name) {
    if (confirm('「' + name + '」の商品を削除しますか？')) {
        document.location = "/sneakers/delete/" + id;
    }
}
</script>

app/views/sneakers/show.html.erb
<h1 class="display-4 text-primary">Sneakers#show</h1>
<p>※「<%= @sneaker.name %>」の商品データ</p>
<table class="table">
    <tr><th width="200">ID</th>
        <td><%= @sneaker.id %></td></tr>
    <tr><th>Name</th>
        <td><%= @sneaker.name %></td></tr>
    <tr><th>Maker</th>
        <td><%= @sneaker.maker %></td></tr>
    <tr><th>Color</th>
        <td><%= @sneaker.color %></td></tr>
    <tr><th>Price</th>
        <td><%= @sneaker.price %>円</td></tr>
    <tr><th>Memo</th>
        <td><%= @sneaker.memo %></td></tr>
</table>
<p><a href="/sneakers">&lt;&lt;※トップページに戻る</a></p>